### ISSUE TITLE
Bad packaging on pypi

### ISSUE THREAD

**Issue by benjaminrene** [jaraco/backports.datetime_timestamp#1] opened 2019-03-14 14:48 UTC
Hello,

There is an issue with the packaging of the lib.

In the tar.gz available on pypi, the path to acces to the tar is `/tmp/tmpe_j4lz0k/backports.datetime_timestamp-1.2.tar` instead of `/dist/backports.datetime_timestamp-1.2.tar`

This package can no longer be installed.

**Comment by jaraco** [comment] 2019-03-15 06:25
Hi Benjamin. Sorry you're having trouble, but it's working for me:

```
~ $ pip-run --no-binary :all: backports.datetime_timestamp                                                                                                                                          
Collecting backports.datetime_timestamp
  Downloading https://files.pythonhosted.org/packages/11/44/5a2a06124392286e15854b4ea63ec5008cca93f94aec1a693b33eea2186d/backports.datetime_timestamp-1.2.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Skipping bdist_wheel for backports.datetime-timestamp, due to binaries being disabled for it.
Installing collected packages: backports.datetime-timestamp
  Running setup.py install for backports.datetime-timestamp ... done
Successfully installed backports.datetime-timestamp-1.2
Python 3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import backports.datetime_timestamp
>>> dir(backports.datetime_timestamp)
['ZERO', '_EPOCH', '_UTC', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_utc', 'datetime', 'time', 'timestamp']
>>> import datetime
>>> backports.datetime_timestamp.timestamp(datetime.datetime.now())
1552630641.252659
```

I used [pip-run](https://pypi.org/project/pip-run) to install the package to a temporary location, but I could just as well have used `pip install` directly.

Furthermore, this project derives from [jaraco/skeleton](/jaraco/skeleton) for its packaging technique, meaning the packages are produced in a mechanical way in an almost identical way to dozens of other projects, so it seems unlikely that this project would have an issue where others do not.

I'm going to close this for now, as I'm unable to reproduce the issue from the description, but do please feel free to elaborate - explain what happened that was unexpected and what you expected to happen. Let me know what commands I can run to produce the unexpected outcome. Maybe try a couple of environments (platforms, Python versions, etc) to see if the problem is localized to one of them.

Thanks and good luck.

**Closed as completed by jaraco** 2019-03-15 06:25 UTC
Labels: invalid
